chore: 🤖 revision and increase timeout to 30 secs

diff --git a/scripts/dev-local-api b/scripts/dev-local-api
--- a/scripts/dev-local-api
+++ b/scripts/dev-local-api
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+envJsonFilename="env.json"
+dotenv=".env"
+lambdaFunctionName="PersonaGeneratorService"
+
 echo "🤖 Development local API..."
 
 if ! command -v sam >/dev/null 2>&1; then
@@ -8,4 +12,27 @@ if ! command -v sam >/dev/null 2>&1; then
   exit 1
 fi
 
-sam build --build-in-source && sam local start-api
+if [[ ! -f "$dotenv" ]]; then
+  echo "👹 Oops! Missing the dotenv file. Check the README, please!"
+
+  exit 1
+fi
+
+source "$dotenv"
+
+if [[ -z "$PRIVATE_OPENAI_COMPATIBLE_API_KEY" || -z "$PUBLIC_OPENAI_COMPATIBLE_API_URL" || -z "$PUBLIC_OPENAI_COMPATIBLE_MODEL" ]]; then
+  echo "👹 Oops! You seem to have failed to provide the required environment variables? Check the README, please!"
+
+  exit 1
+fi
+
+echo "{
+  \"$lambdaFunctionName\": {
+    \"PRIVATE_OPENAI_COMPATIBLE_API_KEY\": \"$PRIVATE_OPENAI_COMPATIBLE_API_KEY\",
+    \"PUBLIC_OPENAI_COMPATIBLE_API_URL\": \"$PUBLIC_OPENAI_COMPATIBLE_API_URL\",
+    \"PUBLIC_OPENAI_COMPATIBLE_MODEL\": \"$PUBLIC_OPENAI_COMPATIBLE_MODEL\"
+  }
+}" > "$envJsonFilename"
+
+sam build --build-in-source
+sam local start-api --debug --env-vars "$envJsonFilename"
